Sources
=======

Code is organized according to the Maven convention in `src/main/java` and
`src/test/java`. In addition Robot Framework test cases for all the keywords
are located in `src/test/resources/robot-tests`


Building
========

SwingLibrary uses Apache Maven_ as a build tool.

__ http://maven.apache.org/

- `mvn package` packages SwingLibrary with dependencies.
- `mvn verify` runs Robot Framework tests.

Releasing
=========

- update `release notes <https://github.com/robotframework/SwingLibrary/wiki/Release-notes>`_
- update version number to pom.xml
- create git tag for new version
- `mvn clean package robotframework:libdoc` generates library docs
- `mvn deploy` deploys the library to maven central. See instructinos on Robot Framework releasing for the prerequisites.
- Go to https://oss.sonatype.org/index.html#welcome, log in with Sonatype creadentials, find the staging repository and do close & release
After that, the released jar is synced to Maven central within an hour.
- upload jar and library docs to github downloads

