Sources
=======

Code is organized according to the Maven convention in `src/main/java` and
`src/test/java`. In addition Robot Framework test cases for all the keywords
are located in `src/test/resources/robot-tests`


Building
========

SwingLibrary uses Apache Maven_ as a build tool.

__ http://maven.apache.org/

- `mvn package` packages SwingLibrary with dependencies.
- `mvn verify` runs Robot Framework tests.

Releasing
=========

- update `release notes <https://github.com/robotframework/SwingLibrary/wiki/Release-notes>`_
- update version number to pom.xml
- create git tag for new version
- `mvn deploy` deploys the library to maven central. See instructions on Robot Framework releasing for the prerequisites.
- Go to https://oss.sonatype.org/index.html#welcome, log in with Sonatype credentials, find the staging repository and do close & release
- XML-spec and library docs are generated automatically by integration-test phase.
- upload jar, library docs, and spec xml to Github downloads


