SwingLibrary
============

Swing Library is a Robot Framework library for testing Java Swing
applications.  Usage instructions are in the Wiki__.

__ https://github.com/robotframework/SwingLibrary/wiki

This project was originally hosted in `Google Code`__

__ http://code.google.com/p/robotframework-swinglibrary/


Building SwingLibrary
---------------------

See BUILD.rest for development, build and release instructions.
