SwingLibrary
============

.. image:: https://travis-ci.org/madworx/SwingLibrary.svg?branch=master
   :target: https://travis-ci.org/madworx/SwingLibrary

Swing Library is a Robot Framework library for testing Java Swing
applications.  Usage instructions are in the Wiki__.

__ https://github.com/robotframework/SwingLibrary/wiki

Downloads are available at `Releases`__

__ https://github.com/madworx/SwingLibrary/releases

Keyword documentation for the latest version (1.9.8) are available `here`__

__ http://robotframework.github.com/SwingLibrary/SwingLibrary-1.9.8.html

This project was originally hosted in `Google Code`__

__ http://code.google.com/p/robotframework-swinglibrary/


Building SwingLibrary
---------------------

See `BUILD.rest`__ for development, build and release instructions.

__ https://github.com/robotframework/SwingLibrary/blob/master/BUILD.rest
